INTERACTIVE_MODELS_PATH: "./weights"
EXPS_PATH: "./experiments"
BACKUP_CKPT: "/content/drive/MyDrive/MVA/2.1.SatelliteIImage/Projet/backup_ckpt/"

# Evaluation datasets
GRABCUT_PATH: "./datasets/GrabCut"
BERKELEY_PATH: "./datasets/Berkeley"
DAVIS_PATH: "./datasets/DAVIS"
COCO_MVAL_PATH: "./datasets/COCO_MVal"
IM_SAT_VAL_SMALL_PATH: "./datasets/IM_SAT_VAL_SMALL"
IM_SAT_VAL_PATH: "./datasets/IM_SAT_VAL"

# Train datasets
SBD_PATH: "./datasets/SBD"
COCO_PATH: "./datasets/coco2017"
LVIS_PATH: "./datasets/LVIS"
OPENIMAGES_PATH: "./datasets/OpenImages"
PASCALVOC_PATH: "./datasets/PascalVOC"
ADE20K_PATH: "./datasets/ADE20K"
IM_SAT_TRAIN_PATH : "./datasets/IM_SAT_TRAIN"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  LAST_CKPT : "./pretrained_models/last_checkpoint.pth"
  HRNETV2_W18_COCOLVIS : "./pretrained_models/coco_lvis_h18_baseline.pth"
  HRNETV2_W18: "./pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
